PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX :       <http://example/>
PREFIX larq:     <http://openjena.org/LARQ/property#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>

SELECT *
{ ?subj larq:search '+document' }
